try {
  alert("hi");
} catch (e) {
  console.log("err", e);
}
